In [1]:
import time
import pandas as pd

from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support.select import Select

In [19]:
path = Service("/Users/shin/chromedriver")
driver = webdriver.Chrome(service=path) #크롬 브라우저 사용

URL = "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&locations=all"
driver.get(URL)
driver.implicitly_wait(time_to_wait=60)

df = pd.DataFrame()

# 스크롤 내리기 이동 전 위치
scroll_location = driver.execute_script("return document.body.scrollHeight")

while True:
    # 현재 스크롤의 가장 아래로 내림 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)") 
    # 전체 스크롤이 늘어날 때까지 대기 
    time.sleep(2) 
    # 늘어난 스크롤 높이 
    scroll_height = driver.execute_script("return document.body.scrollHeight") 
    # 늘어난 스크롤 위치와 이동 전 위치 같으면(더 이상 스크롤이 늘어나지 않으면) 종료 
    if scroll_location == scroll_height:
        break 
    # 같지 않으면 스크롤 위치 값을 수정하여 같아질 때까지 반복 
    else: # 스크롤 위치값을 수정
        scroll_location = driver.execute_script("return document.body.scrollHeight")
    break
        
div = driver.find_elements(By.CLASS_NAME, "Card_className__u5rsb")
for item in div:
    link = item.find_element(By.TAG_NAME, "a").get_attribute('href')
    tmp = pd.DataFrame([link])
    df = pd.concat([df, tmp])
    
driver.close()

df.to_csv('Book.csv', index=False)

In [17]:
df_link = pd.read_excel('/Users/shin/Book1.xlsx')
df_link

                                    link
0     https://www.wanted.co.kr/wd/102216
1     https://www.wanted.co.kr/wd/104638
2     https://www.wanted.co.kr/wd/104693
3     https://www.wanted.co.kr/wd/104695
4     https://www.wanted.co.kr/wd/104627
...                                  ...
5553   https://www.wanted.co.kr/wd/50311
5554   https://www.wanted.co.kr/wd/63074
5555   https://www.wanted.co.kr/wd/70201
5556   https://www.wanted.co.kr/wd/70258
5557   https://www.wanted.co.kr/wd/63903

[5558 rows x 1 columns]

In [25]:
path = Service("/Users/shin/chromedriver")
driver = webdriver.Chrome(service=path)

df = pd.DataFrame(columns=["header", "detail"])

for URL in df_link['link']:
    
    driver.get(URL)
    driver.implicitly_wait(time_to_wait=60)

    header = driver.find_element(By.CLASS_NAME, "JobHeader_className__HttDA")
    detail = driver.find_element(By.CLASS_NAME, "JobContent_descriptionWrapper__SM4UD")

    tmp = pd.DataFrame({"header":[header.text],
                        "detail":[detail.text]})
    df = pd.concat([df, tmp])
    time.sleep(1)
    
driver.close()

df

,header,detail
0,프론트/백엔드 개발자\n메이크스타\n응답률 높음\n서울.한국\n#인원급성장#50명이...,"BTS, 오징어게임, 기생충 등으로 대표되는 우리나라의 문화 콘텐츠는 참신성과 혁신..."
0,Server Engineer\n에이톤\n응답률 평균 이상\n서울.한국\n#스타트업#...,"""No Contents, No Life""\n\nPulit은 「크리에이터들의 기존 플..."
0,Android Engineer\n에이톤\n응답률 평균 이상\n서울.한국\n#스타트업...,"""No Contents, No Life""\n\nPulit은 「크리에이터들의 기존 플..."
0,iOS Engineer\n에이톤\n응답률 평균 이상\n서울.한국\n#스타트업#재택근...,"""No Contents, No Life""\n\nPulit은 「크리에이터들의 기존 플..."
0,인공지능 대화 서비스 파트 JAVA 개발자\n피플앤드테크놀러지\n응답률 평균 이상\...,[피플앤드테크놀러지는 차별화된 기술력과 업계 최고의 업력을 자랑하는 IoT(사물인터...
...,...,...
0,프론트 개발자\nGymT(짐티)\n서울.한국\n#퇴사율5%이하#50명이하#설립4~9...,[비전]\nSound Body Sound Mind!\n건강한 몸에서 건강한 정신이 ...
0,"SE팀-시스템 담당 (OS 및 서비스, 네트웍장비 등)\n로지올(LOGiALL)\n...","하얀색 박스에 ""생각대로""라는 로고가 찍힌 오토바이를 보신 적 있으신가요?\n좀 촌..."
0,모바일개발팀-안드로이드 (Android) Native 앱 배달 플랫폼 서비스 개발\...,"""생각대로""라는 로고가 적혀있는 배달 오토바이를 보신 적 있으신가요?\n그 오토바이..."
0,"가맹개발팀-가맹점 PC Windows Server, Application 개발\n로...","""생각대로""라는 로고가 적혀있는 배달 오토바이를 보신 적 있으신가요?\n그 오토바이..."
0,API 서버 / Web Site 개발 및 유지보수\n로지올(LOGiALL)\n서울....,"붉은색의 ""생각대로""라는 로고가 적혀있는 배달 오토바이를 보신 적 있으신가요?\n그..."

In [26]:
df.to_csv("wanted_crawling_data.csv", index=False)