In [1]:
import time
import pandas as pd

from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support.select import Select

In [19]:
path = Service("/Users/shin/chromedriver")
driver = webdriver.Chrome(service=path) #크롬 브라우저 사용

URL = "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&locations=all"
driver.get(URL)
driver.implicitly_wait(time_to_wait=60)

df = pd.DataFrame()

# 스크롤 내리기 이동 전 위치
scroll_location = driver.execute_script("return document.body.scrollHeight")

while True:
    # 현재 스크롤의 가장 아래로 내림 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)") 
    # 전체 스크롤이 늘어날 때까지 대기 
    time.sleep(2) 
    # 늘어난 스크롤 높이 
    scroll_height = driver.execute_script("return document.body.scrollHeight") 
    # 늘어난 스크롤 위치와 이동 전 위치 같으면(더 이상 스크롤이 늘어나지 않으면) 종료 
    if scroll_location == scroll_height:
        break 
    # 같지 않으면 스크롤 위치 값을 수정하여 같아질 때까지 반복 
    else: # 스크롤 위치값을 수정
        scroll_location = driver.execute_script("return document.body.scrollHeight")
    break
        
div = driver.find_elements(By.CLASS_NAME, "Card_className__u5rsb")
for item in div:
    link = item.find_element(By.TAG_NAME, "a").get_attribute('href')
    tmp = pd.DataFrame([link])
    df = pd.concat([df, tmp])
    
driver.close()

df.to_csv('Book.csv', index=False)

In [17]:
df_link = pd.read_excel('/Users/shin/Book1.xlsx')
df_link

                                    link
0     https://www.wanted.co.kr/wd/102216
1     https://www.wanted.co.kr/wd/104638
2     https://www.wanted.co.kr/wd/104693
3     https://www.wanted.co.kr/wd/104695
4     https://www.wanted.co.kr/wd/104627
...                                  ...
5553   https://www.wanted.co.kr/wd/50311
5554   https://www.wanted.co.kr/wd/63074
5555   https://www.wanted.co.kr/wd/70201
5556   https://www.wanted.co.kr/wd/70258
5557   https://www.wanted.co.kr/wd/63903

[5558 rows x 1 columns]

In [25]:
path = Service("/Users/shin/chromedriver")
driver = webdriver.Chrome(service=path)

df = pd.DataFrame(columns=["header", "detail"])

for URL in df_link['link']:
    
    driver.get(URL)
    driver.implicitly_wait(time_to_wait=60)

    header = driver.find_element(By.CLASS_NAME, "JobHeader_className__HttDA")
    detail = driver.find_element(By.CLASS_NAME, "JobContent_descriptionWrapper__SM4UD")

    tmp = pd.DataFrame({"header":[header.text],
                        "detail":[detail.text]})
    df = pd.concat([df, tmp])
    time.sleep(1)
    
driver.close()

df

,header,detail
0,프론트/백엔드 개발자\n메이크스타\n응답률 높음\n서울.한국\n#인원급성장#50명이...,"BTS, 오징어게임, 기생충 등으로 대표되는 우리나라의 문화 콘텐츠는 참신성과 혁신..."
0,Server Engineer\n에이톤\n응답률 평균 이상\n서울.한국\n#스타트업#...,"""No Contents, No Life""\n\nPulit은 「크리에이터들의 기존 플..."
0,Android Engineer\n에이톤\n응답률 평균 이상\n서울.한국\n#스타트업...,"""No Contents, No Life""\n\nPulit은 「크리에이터들의 기존 플..."
0,iOS Engineer\n에이톤\n응답률 평균 이상\n서울.한국\n#스타트업#재택근...,"""No Contents, No Life""\n\nPulit은 「크리에이터들의 기존 플..."
0,인공지능 대화 서비스 파트 JAVA 개발자\n피플앤드테크놀러지\n응답률 평균 이상\...,[피플앤드테크놀러지는 차별화된 기술력과 업계 최고의 업력을 자랑하는 IoT(사물인터...
...,...,...
0,프론트 개발자\nGymT(짐티)\n서울.한국\n#퇴사율5%이하#50명이하#설립4~9...,[비전]\nSound Body Sound Mind!\n건강한 몸에서 건강한 정신이 ...
0,"SE팀-시스템 담당 (OS 및 서비스, 네트웍장비 등)\n로지올(LOGiALL)\n...","하얀색 박스에 ""생각대로""라는 로고가 찍힌 오토바이를 보신 적 있으신가요?\n좀 촌..."
0,모바일개발팀-안드로이드 (Android) Native 앱 배달 플랫폼 서비스 개발\...,"""생각대로""라는 로고가 적혀있는 배달 오토바이를 보신 적 있으신가요?\n그 오토바이..."
0,"가맹개발팀-가맹점 PC Windows Server, Application 개발\n로...","""생각대로""라는 로고가 적혀있는 배달 오토바이를 보신 적 있으신가요?\n그 오토바이..."
0,API 서버 / Web Site 개발 및 유지보수\n로지올(LOGiALL)\n서울....,"붉은색의 ""생각대로""라는 로고가 적혀있는 배달 오토바이를 보신 적 있으신가요?\n그..."

In [26]:
df.to_csv("wanted_crawling_data.csv", index=False)

In [28]:
path = Service("/Users/shin/chromedriver")
driver = webdriver.Chrome(service=path) #크롬 브라우저 사용
# AI: 머신러닝 엔지니어, 데이터 사이언티스트, 빅데이터 엔지니어, BI 엔지니어
URL = "https://www.wanted.co.kr/wdlist/518?selected=1634&selected=1024&selected=1025&selected=1022"
# Game: VR 엔지니어
# "https://www.wanted.co.kr/wdlist/518/10112?country=kr&job_sort=company.response_rate_order&years=-1&locations=all"

# Service: CIO
# "https://www.wanted.co.kr/wdlist/518/793?country=kr&job_sort=company.response_rate_order&years=-1&locations=all"
# Service: 개발 메니저, QA 테스트 엔지니어, 기술지원, 프로덕트 메니저, ERP 전문가
# "https://www.wanted.co.kr/wdlist/518?selected=877&selected=676&selected=1026&selected=876&selected=10230"

# Application: 안드로이드 개발자, iOS 개발자, 크로스 플랫폼 앱 개발자
# "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&selected=677&selected=678&selected=10111&locations=all"

# Front-End: 프론트엔드 개발자, 웹 퍼블리셔
# "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&selected=669&selected=939&locations=all"

# Network/Security: 서버 개발자, 시스템/네트워크 개발자, 보안 엔지니어
# "https://www.wanted.co.kr/wdlist/518?selected=872&selected=665&selected=671"

# DataBase: 데이터 엔지니어, DBA
# "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&selected=655&selected=10231&locations=all"

# System: DevOps/시스템 개발자, 시스템/네트워크 개발자, 임베디드 개발자, 하드웨어 개발자
# "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&selected=674&selected=665&selected=658&selected=672&locations=all"

# Software: 소프트웨어 엔지니어, 자바 개발자, 파이썬 개발자, C,C++ 개발자, .NET 개발자
# "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&selected=10110&selected=660&selected=899&selected=900&selected=661&locations=all"

# Back-end: 루비 온레일즈 개발자
# "https://www.wanted.co.kr/wdlist/518/894?country=kr&job_sort=company.response_rate_order&years=-1&locations=all"
# Back-end: 웹 개발자, Node.js 개발자, PHP 개발자, 블록체인 플랫폼 엔지니어, CTO 
# "https://www.wanted.co.kr/wdlist/518?country=kr&job_sort=company.response_rate_order&years=-1&selected=872&selected=895&selected=893&selected=1027&selected=795&locations=all"
driver.get(URL)
driver.implicitly_wait(time_to_wait=60)

df = pd.DataFrame()

# 스크롤 내리기 이동 전 위치
scroll_location = driver.execute_script("return document.body.scrollHeight")

while True:
    # 현재 스크롤의 가장 아래로 내림 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)") 
    # 전체 스크롤이 늘어날 때까지 대기 
    time.sleep(2)
    # 늘어난 스크롤 높이 
    scroll_height = driver.execute_script("return document.body.scrollHeight") 
    # 늘어난 스크롤 위치와 이동 전 위치 같으면(더 이상 스크롤이 늘어나지 않으면) 종료 
    if scroll_location == scroll_height:
        break 
    # 같지 않으면 스크롤 위치 값을 수정하여 같아질 때까지 반복 
    else: # 스크롤 위치값을 수정
        scroll_location = driver.execute_script("return document.body.scrollHeight")

time.sleep(1)
div = driver.find_elements(By.CLASS_NAME, "Card_className__u5rsb")
for item in div:
    link = item.find_element(By.TAG_NAME, "a").get_attribute('href')
    tmp = pd.DataFrame([link])
    df = pd.concat([df, tmp])
    
driver.close()

df.to_csv('AI.csv', index=False)

In [26]:
pd.concat([pd.read_csv("Service_1.csv"), pd.read_csv("Service_2.csv")]).to_csv("Service.csv", index=False)

In [2]:
from tqdm import tqdm

_class = ["Back-end", "Software", "System", "DataBase", "Network_Security", 
          "Front-End", "Application", "Service", "Game", "AI"]

path = Service("/Users/shin/chromedriver")
driver = webdriver.Chrome(service=path)
df = pd.DataFrame(columns=["header", "detail"])

for c in _class:
    name = c+".csv"
    df_link = pd.read_csv(name)

    for URL in tqdm(df_link['0']):
        driver.get(URL)
        driver.implicitly_wait(time_to_wait=60)

        # header = driver.find_element(By.CLASS_NAME, "JobHeader_className__HttDA")
        detail = driver.find_element(By.CLASS_NAME, "JobContent_descriptionWrapper__SM4UD")

        tmp = pd.DataFrame({"header":[c],
                            "detail":[detail.text]})
        df = pd.concat([df, tmp])
        time.sleep(1)

driver.close()
df

100%|█████████████████████████████████████| 2265/2265 [1:43:04<00:00,  2.73s/it]
100%|█████████████████████████████████████| 2891/2891 [1:31:42<00:00,  1.90s/it]
100%|█████████████████████████████████████████| 619/619 [19:52<00:00,  1.93s/it]
100%|█████████████████████████████████████████| 378/378 [12:03<00:00,  1.91s/it]
100%|███████████████████████████████████████| 1578/1578 [52:02<00:00,  1.98s/it]
100%|███████████████████████████████████████| 1517/1517 [49:32<00:00,  1.96s/it]
100%|███████████████████████████████████████| 1053/1053 [34:22<00:00,  1.96s/it]
100%|█████████████████████████████████████████| 836/836 [26:39<00:00,  1.91s/it]
100%|███████████████████████████████████████████| 37/37 [01:16<00:00,  2.06s/it]
100%|█████████████████████████████████████████| 760/760 [24:00<00:00,  1.90s/it]

      header                                             detail
0   Back-end  한국문화를 알리고 한글을 가르치고, 사람들과 소통하며, 상품 구매도 가능한 APP개...
0   Back-end  안녕하세요, 저희는 누구나 손쉽게 사용할 수 있는 '인공지능 자동개발 플랫폼' [D...
0   Back-end  안녕하세요? 계속적으로 성장하는 시니어 웰니스 플랫폼 스타트업 후케어스입니다.\n개...
0   Back-end  "인간과 공감하는 인공지능을 향한 꿈, 그 꿈을 향한 데이터 솔루션"\n\n미디어 ...
0   Back-end  닥프렌즈는 모두가 주치의와 연결되는 플랫폼을 만듭니다. \n\n환자와 의사가 연결되...
..       ...                                                ...
0         AI  디우스는 철도분야 코스닥 상장사의 자회사로 철도 분야의 Digital Transfo...
0         AI  솔로몬테크노서플라이는 2012년에 설립된 회사로 자본금 6억원, 매출액 434억 4...
0         AI  Dynamic New Entertainment Creation SpecialisT\...
0         AI  하이디어 솔루션즈는 시니어케어 및 키즈케어 등의 M2M, IoT(Internet o...
0         AI  NFT뱅크는 (전) 그라운드X (카카오 블록체인), 페이스북 출신들로 구성된 블록체...

[11934 rows x 2 columns]

In [3]:
df.to_csv("renewal_wanted_crawling.csv", index=False)